name: secure_it
description: A SecureIT project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  sizer: ^2.0.15
  get: ^4.6.5
  flutter_launcher_icons: ^0.10.0
  provider: ^6.0.3
  intl: ^0.17.0
  # auto_route: ^5.0.1
  badges: ^2.0.3
  smooth_page_indicator: ^1.0.0+2
  google_maps_flutter: ^2.2.0
  flutter_zoom_drawer: ^3.0.3
  circular_profile_avatar: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/

